services:
  ollama:
    image: ollama/ollama
    #runtime: nvidia
    container_name: ollama_service
    ports:
      - "11434:11434"
    restart: always
    volumes:
      - ./.ollama:/root/.ollama
    environment:
      - OLLAMA_ACCELERATE=true
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
  
  ollama-langchain:
    build: .
    #runtime: nvidia
    #deploy:
      #resources:
        #reservations:
          #devices:
            #- driver: nvidia
              #count: all
              #capabilities: [gpu]
    environment:
      - OLLAMA_ACCELERATE=true
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
  app:
    build: .
    container_name: fastapi_chatbot
    ports:
      - "8000:8000"
    depends_on:
      - ollama
      - ollama-langchain
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - .:/app
      
volumes:
  ollama_data: 